DELETE http://localhost:3003/api/blogs/64047ca3c38b1bef501c9e0c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1tZWlrYWxhIiwiaWQiOiI2NDAwOTRlMTBmZjYyMjc0NGZlNTBiMzUiLCJpYXQiOjE2NzgwMTU5MzMsImV4cCI6MTY3ODAxOTUzM30.7ceCofPyxq6E0Fcs643rM_s6q6eBPKLOJlzO-SoZ_X8